services:
  web-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev-web-service
    hostname: dev-web-service
    ports:
      - "8000:8000"
    env_file:
      - ./env/web/django/.env.development
      - ./env/processing/core/.env.development
    environment:
      - ENVIRONMENT=development
      - DATABASE_HOST=dev-db-service
      - REDIS_HOST=dev-cache-service
    depends_on:
      - db-service
      - cache-service
    volumes:
      - .:/app
      - ./test_data:/app/test_data
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    networks:
      - excel-dev-network

  db-service:
    image: postgres:16-alpine
    container_name: dev-db-service
    hostname: dev-db-service
    env_file:
      - ./env/database/postgresql/.env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - excel-dev-network

  cache-service:
    image: redis:7.4-alpine
    container_name: dev-cache-service
    hostname: dev-cache-service
    env_file:
      - ./env/cache/redis/.env.development
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - excel-dev-network

networks:
  excel-dev-network:
    driver: bridge

volumes:
  postgres_dev_data: